Add release scripts for both build repo and image
openshift/hac-core pull request #11
Opened 2021-12-07 13:53 UTC by karelhala

2021-12-07 16:02 UTC, andrewballantyne requested changes

2021-12-07 16:03 UTC, andrewballantyne commented on release-build-repo.sh
> +mkdir -p ./.travis
Oh and same here... gitignore?

2021-12-07 16:04 UTC, karelhala commented on release-image.sh
> +mkdir -p ./scripts
Mhh, we can't change the folder name as it's used in the scripts. But I'll gitignore!

2021-12-07 16:05 UTC, andrewballantyne commented on release-image.sh
> +mkdir -p ./scripts
Yeah, maybe add a comment above it saying what it is... just so there is no "well this isn't used, I'll delete" thoughts later

2021-12-07 16:07 UTC, andrewballantyne commented on .gitignore
> +frontend/.travis
yeah, maybe a comment here that it's used by the CI

2021-12-09 13:59 UTC, andrewballantyne approved these changes

2021-12-09 14:03 UTC, merged