Add option to load plugin from different route, enhance route picking
openshift/hac-core pull request #2
Opened 2021-11-23 10:59 UTC by karelhala

### Load plugin from different route

Since we want to support additional apps to enhance our UI we should add a way how to determine from which source each plugin actually comes. This PR adds such support by including `pathPrefix` to each enabled plugins, this way we can pull plugins from console.redhat.com applications as well. This will require the app to expose such plugins via Webpack plugin (work already done in https://github.com/RedHatInsights/frontend-components/pull/1316)

### Enhance route picking

Since we don't want to fully rely only on first and second part of URL we can utilize [react-router#matchPath](https://v5.reactrouter.com/web/api/matchPath) to calculate if route fits our needs. With slight addition of section to prepend the path from plugin to determine if plugin comes from section (feature enhancements should fully look at section route is supposed to mount into).

2021-11-23 10:59 UTC, karelhala commented
ping @andrewballantyne

2021-11-23 14:29 UTC, andrewballantyne commented
@karelhala I'm getting a Gateway error... is there anything else I need to do to setup things?

> https://ci.foo.redhat.com:1337/apps/sources/plugin-manifest.json
> Error occured while trying to proxy to: ci.foo.redhat.com:1337/apps/sources/plugin-manifest.json

2021-11-23 15:54 UTC, andrewballantyne commented
/assign

2021-11-23 17:45 UTC, andrewballantyne requested changes
Looking great, just a slew of type suggestions to help it be more clear and direct. Let me know if you have any questions.

---

I also added some globals to eslint to get around the oddity with these Promise types & eslint.

```
  globals: {
    ...
    PromiseSettledResult: 'readonly',
    PromiseFulfilledResult: 'readonly',
    PromiseRejectedResult: 'readonly',
  },
```

2021-11-23 17:45 UTC, andrewballantyne commented on frontend/src/Navigation.ts
> +      }
I think we want it to explode... it'll reject the promise for us. 

Might want to do something like:
```
  results.filter(isRejectedPromise).forEach((e) => {
    // eslint-disable-next-line no-console
    console.error('Failed to fetch plugin-manifest', e.reason);
  });
```

Type-guard:
```
const isRejectedPromise = (result: PromiseSettledResult<Extension[]>): result is PromiseRejectedResult => {
  return result.status === 'rejected';
};
```

2021-11-23 17:45 UTC, andrewballantyne commented on frontend/src/Navigation.ts
> +        const manifest = await (await fetch(`${pathPrefix}/${pluginName}/plugin-manifest.json`))?.json();
```
import { ConsolePluginManifestJSON } from '@console/dynamic-plugin-sdk/src/schema/plugin-manifest';
```

```suggestion
        const manifest: ConsolePluginManifestJSON = await (await fetch(`${pathPrefix}/${pluginName}/plugin-manifest.json`))?.json();
```

2021-11-23 17:45 UTC, andrewballantyne commented on frontend/src/Navigation.ts
> +      }
Upon playing with it more, I went with this:

```
  const results: PromiseSettledResult<Extension[]>[] = await Promise.allSettled(
    activePlugins.flatMap(async ({ name: pluginName, pathPrefix = '/api/plugins' }: EnabledPlugin) => {
      const url = `${pathPrefix}/${pluginName}/plugin-manifest.json`;
      const response: Response = await fetch(url);
      if (response.status !== 200) {
        throw new Error(`${url} - ${response.status} - ${response.statusText}`);
      }
      const manifest: ConsolePluginManifestJSON = await response.json();
      return manifest.extensions;
    }),
  );
```
Let me know what you think.

2021-11-24 15:53 UTC, karelhala commented on frontend/src/Navigation.ts
> +  .filter(({ type }) => ['console.navigation/href', 'console.navigation/section'].includes(type));
Looking good! I've also added a check in the `isFulfilledPromise` to check for existing value. If the manifest is just empty we don't want to deal with it either.

2021-11-24 16:06 UTC, andrewballantyne approved these changes

2021-11-24 16:07 UTC, merged