Switch dev to start on stage
openshift/hac-core pull request #22
Opened 2022-01-13 09:28 UTC by karelhala

2022-01-13 21:19 UTC, andrewballantyne commented
/assign

I gotta still setup my env... will review this with that effort.

2022-01-18 14:32 UTC, andrewballantyne requested changes
Looking good... do we want to strip `ci, qa` out from the `release-build-repo.sh`?

2022-01-18 14:38 UTC, karelhala commented
@andrewballantyne good point!

2022-01-18 14:49 UTC, andrewballantyne approved these changes

2022-01-18 15:00 UTC, merged